name: autofix.ci
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: autofix-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          disk-cache: autofix
          cache-save: ${{ github.ref == 'refs/heads/main' }}

      - name: Format
        run: bazel run //tools/format

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
