name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile

      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.ref == 'refs/heads/main' }}

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
