name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup
        with:
          disk-cache: ${{ github.workflow }}
          cache-save: ${{ github.ref == 'refs/heads/main' }}

      - name: Install playwright
        run: |
          cd apps/frontend && pnpm exec playwright install --with-deps chromium
        continue-on-error: false

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
